const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const fields=['matter','asof','actor','jurisdiction','question','limits','sourceTitle','issuer','authority','posture','proposition','identifier','pinpoint','level','body','issued','effective','checked','status','trail','comparable','differences','confidence','disposition','answer','unresolved','escalation'];
const state={step:0,done:[false,false,false,false,false],rows:[{place:'',rule:'',difference:''}]};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function collect(){fields.forEach(k=>{const el=$('#'+k);if(el)state[k]=el.value});state.done=$$('[data-done]').map(x=>x.checked);$$('[data-row]').forEach(el=>state.rows[+el.dataset.row][el.dataset.key]=el.value)}
function save(){collect();localStorage.setItem('regac-academy-v2',JSON.stringify(state));$('#save').textContent='Saved · '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});progress()}
function restore(){try{Object.assign(state,JSON.parse(localStorage.getItem('regac-academy-v2'))||{});fields.forEach(k=>{const el=$('#'+k);if(el&&state[k]!=null)el.value=state[k]});$$('[data-done]').forEach((x,i)=>x.checked=!!state.done[i])}catch(e){}}
function show(n){state.step=Math.max(0,Math.min(5,n));$$('.panel').forEach((x,i)=>x.classList.toggle('active',i===state.step));$$('.tab').forEach((x,i)=>x.classList.toggle('active',i===state.step));if(state.step===5)packet();save();location.hash='academy'}
function progress(){const done=state.done.filter(Boolean).length,p=Math.round(done/5*100);$('#percent').textContent=p+'%';$('#progressText').textContent=done+' of 5 learning gates complete';$('#bar').style.width=p+'%'}
function renderRows(){if(!state.rows?.length)state.rows=[{place:'',rule:'',difference:''}];$('#rows').innerHTML=state.rows.map((r,i)=>'<div class="compareRow"><input aria-label="Jurisdiction" placeholder="Jurisdiction / regime" data-row="'+i+'" data-key="place" value="'+esc(r.place)+'"><input aria-label="Rule or status" placeholder="Rule / status + as-of date" data-row="'+i+'" data-key="rule" value="'+esc(r.rule)+'"><input aria-label="Material difference" placeholder="Exception / material difference" data-row="'+i+'" data-key="difference" value="'+esc(r.difference)+'"><button aria-label="Remove row" data-remove="'+i+'">×</button></div>').join('')}
function authorityPrompt(){const a=$('#authority').value,p=$('#posture').value,id=$('#identifier').value,pin=$('#pinpoint').value;let msg='Complete the classification to generate a review prompt.';if(a){msg=(a.includes('proposal')||a.includes('Pending'))?'This is not effective law. Record legislative or rulemaking status and do not describe it as a current requirement.':a==='Official guidance'?'Guidance may describe agency interpretation without carrying the force of a statute or regulation. Check enabling authority and disclaim nonbinding posture.':'Verify issuer, jurisdiction, operative status, later history, and the exact proposition supported.';if(!id||!pin)msg+=' Add an official identifier and pinpoint so another reviewer can reproduce the check.'}$('#authorityFeedback').textContent=msg}
function completeness(){collect();const required=['matter','asof','jurisdiction','question','sourceTitle','issuer','authority','identifier','pinpoint','checked','trail','comparable','differences','answer','unresolved','escalation'];const values=required.filter(k=>String(state[k]||'').trim()).length;return Math.round((values+state.done.filter(Boolean).length)/(required.length+5)*100)}
function packet(){collect();const score=completeness();$('#score').textContent=score+'%';$('#outDisposition').textContent=state.disposition||'Hold';$('#outDate').textContent=state.asof||'Not set';const sections=[
['Research boundary',[['Matter',state.matter],['Actor / audience',state.actor],['Jurisdiction',state.jurisdiction],['As-of',state.asof],['Question',state.question],['Known limits',state.limits]]],
['Authority record',[['Source',state.sourceTitle],['Issuer',state.issuer],['Class',state.authority],['Posture',state.posture],['Identifier',state.identifier],['Pinpoint',state.pinpoint],['Proposition',state.proposition]]],
['Currentness record',[['Level',state.level],['Responsible body',state.body],['Issued',state.issued],['Effective',state.effective],['Last checked',state.checked],['Status',state.status],['Trail',state.trail]]],
['Comparison',[['Comparable dimension',state.comparable],['Differences preserved',state.differences],['Regimes',state.rows.map(r=>[r.place,r.rule,r.difference].filter(Boolean).join(' — ')).filter(Boolean).join('; ')]]],
['Disposition',[['Confidence',state.confidence],['Decision',state.disposition],['Proposed answer',state.answer],['Unresolved',state.unresolved],['Escalation',state.escalation]]]];
$('#packet').innerHTML=sections.map(([h,items])=>'<article><h3>'+h+'</h3>'+items.map(([k,v])=>'<p><strong>'+k+':</strong> '+esc(v||'Not documented')+'</p>').join('')+'</article>').join('')}
function markdown(){packet();return '# REGAC Regulatory Research Field Packet\n\nGenerated '+new Date().toISOString()+'\n\n'+$$('#packet article').map(a=>'## '+a.querySelector('h3').textContent+'\n'+[...a.querySelectorAll('p')].map(p=>'- '+p.textContent).join('\n')).join('\n\n')+'\n\n## Use boundary\nEducational research record only. It does not determine applicable law, certify currentness, or replace qualified jurisdiction-specific review.\n'}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
document.addEventListener('input',e=>{if(e.target.matches('[data-row]'))state.rows[+e.target.dataset.row][e.target.dataset.key]=e.target.value;authorityPrompt();save()});
document.addEventListener('change',save);
document.addEventListener('click',e=>{if(e.target.matches('.next'))show(state.step+1);if(e.target.matches('.prev'))show(state.step-1);if(e.target.matches('.tab'))show(+e.target.dataset.step);if(e.target.dataset.remove!=null){state.rows.splice(+e.target.dataset.remove,1);renderRows();save()}});
$('#addRow').onclick=()=>{state.rows.push({place:'',rule:'',difference:''});renderRows();save()};
$('#md').onclick=()=>download('regac-field-packet.md',markdown(),'text/markdown');
$('#csv').onclick=()=>{collect();download('regac-jurisdiction-comparison.csv',['jurisdiction,rule_or_status,material_difference',...state.rows.map(r=>[r.place,r.rule,r.difference].map(v=>'"'+String(v||'').replaceAll('"','""')+'"').join(','))].join('\n'),'text/csv')};
$('#json').onclick=()=>{collect();download('regac-backup.json',JSON.stringify({version:'2.0',exportedAt:new Date().toISOString(),record:state},null,2),'application/json')};
$('#reset').onclick=()=>{if(confirm('Clear this browser’s saved academy record?')){localStorage.removeItem('regac-academy-v2');location.reload()}};
$('#example').onclick=()=>{Object.assign(state,{matter:'Cannabis product advertising research exercise',asof:new Date().toISOString().slice(0,10),actor:'Multistate operator research team',jurisdiction:'Federal plus selected state and local regimes',question:'Which authority controls each proposed advertising statement and what jurisdiction-specific limits require counsel review?',limits:'Illustrative learning record; source retrieval and jurisdiction-specific legal review remain required.',sourceTitle:'Illustrative agency advertising guidance',issuer:'State regulatory agency',authority:'Official guidance',posture:'Interpretive/nonbinding',proposition:'The agency describes its current interpretation of selected advertising restrictions.',identifier:'Official agency URL required',pinpoint:'Section and page required',level:'State/territory',body:'Regulatory agency',checked:new Date().toISOString().slice(0,10),status:'Unverified',trail:'Retrieve official version, enabling statute and regulations; check amendments, orders, FAQs and litigation.',comparable:'Compare definitions, prohibited claims, audience/location rules, approval requirements and effective dates.',differences:'Do not collapse statutes, rules, guidance, enforcement practice, local overlays or proposed changes.',confidence:'Low—material gaps',disposition:'Escalate to qualified reviewer',answer:'Hold any operational conclusion until primary sources and later history are checked.',unresolved:'Applicable local overlays, factual product classification, later amendments and enforcement posture.',escalation:'Licensed counsel reviews before publication or operational use.',done:[true,true,false,true,true],rows:[{place:'Jurisdiction A',rule:'Retrieve current statute/rule',difference:'Definitions and local overlay pending'},{place:'Jurisdiction B',rule:'Official source review pending',difference:'Approval process may differ'}]});fields.forEach(k=>{const el=$('#'+k);if(el&&state[k]!=null)el.value=state[k]});$$('[data-done]').forEach((x,i)=>x.checked=!!state.done[i]);renderRows();authorityPrompt();save();show(5)};
restore();renderRows();authorityPrompt();show(state.step||0);